kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/vcs-ref: develop
    app.openshift.io/vcs-uri: 'https://github.com/cristobal-tudela-ruiz/udemy-apps-openshift.git'
    openshift.io/generated-by: OpenShiftWebConsole
  name: sonarqube
  labels:
    app: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
        - name: sonarqube
          image: >-
            image-registry.openshift-image-registry.svc:5000/devops-tools/sonarqube:9.9-community
          ports:
            - containerPort: 9000
              protocol: TCP
          resources:
            limits:
              cpu: 1500m
              memory: 1800Mi
            requests:
              cpu: 90m
              memory: 1800Mi
          volumeMounts:
          - mountPath: /opt/sonarqube/data
            name: sonarqube-data
            subPath: data
          - mountPath: /opt/sonarqube/logs
            name: sonarqube-data
            subPath: logs
          - mountPath: /opt/sonarqube/extensions
            name: sonarqube-data
            subPath: extensions
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
      volumes:
        - name: sonarqube-data
          persistentVolumeClaim:
            claimName: sonarqube-data
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
