kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: develop
    app.openshift.io/vcs-uri: 'https://github.com/cristobal-tudela-ruiz/udemy-apps-openshift.git'
    openshift.io/generated-by: OpenShiftWebConsole
  name: sonarqube
  labels:
    app: sonarqube
spec:
  lookupPolicy:
    local: false
  tags:
    - annotations:
        openshift.io/generated-by: OpenShiftWebConsole
        openshift.io/imported-from: 'sonarqube:9.9-community'
      from:
        kind: DockerImage
        name: 'sonarqube:9.9-community'
      importPolicy: {}
      name: 9.9-community
      referencePolicy:
        type: Source
